local PlayerControlSystem = require('src/ecs/systems/player_control_system')

describe('Player Control System', function()
	it('can be instantiated.', function()
		assert.has_no_errors(function()
			PlayerControlSystem:update()
		end)
	end)
	--it('updates the player position.', function ()
	--	PlayerControlSystem:update(1)
	--end)
	--it('has the correct name.', function ()
	--	assert.is_true(PositionComponent:getName() == "position")
	--end)
end)