local PositionComponent = require('src/ecs/components/position_component')

describe('Position Component', function()
	it('can be instantiated safely.', function()
		assert.has_no_errors(function()
			PositionComponent:hasName()
		end)
	end)
 	it("is like a Highlander; there can be only one.", function()    	
    	assert.is_true(PositionComponent == require('src/ecs/components/position_component'))
  	end)
	it('has a name.', function ()
		assert.is_true(PositionComponent:hasName())
	end)
	it('has the correct name.', function ()
		assert.is_true(PositionComponent:getName() == "position")
	end)
end)