local Player = require('src/ecs/entities/player')
local PositionComponent = require('src/ecs/components/position_component')

describe('Player', function()
	it('can be instantiated safely.', function()
		assert.has_no_errors(function() Player:new() end)
	end)
	it('has a position component.', function()
		assert.is.truthy(Player:new().position)
	end)
end)