name: develop

on:
  push:
    branches:
      - develop
      - 'feature/**'
  pull_request:
    branches:
      - 'bug/**'
      - 'task/**'

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: leafo/gh-actions-lua@v9
      - uses: leafo/gh-actions-luarocks@v4
      - uses: actions/checkout@v2
      - name: Tree
        run: |
          sudo apt install tree
          tree ../../../../../
      #- name: Install LDoc
      #  run: |
      #    luarocks install --local ldoc

      #- name: Install Love
      #  run: |
      #    sudo add-apt-repository ppa:bartbes/love-stable
      #    sudo apt-get update
      #- name: Run LDoc
      #  run: ldoc .

      #- name: Deploy Docs
      #  uses: peaceiris/actions-gh-pages@v3
      #  if: ${{ github.ref == 'refs/heads/develop' }}
      #  with:
      #    github_token: ${{ secrets.GITHUB_TOKEN }}
      #    publish_dir: ./doc

  #build:
  #  runs-on: ubuntu-latest

  #  steps:
  #    - uses: actions/checkout@v2
  #    - uses: nhartland/love-build@v1-beta3
  #      with:
  #        app_name: 'love-bed'
  #        love_version: '11.3'
  #        source_dir: '.'
  #    - uses: actions/upload-artifact@v1
  #      with:
  #        name: built-application
  #        path: 'release'
