name: main

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: leafo/gh-actions-lua@v9
      - uses: leafo/gh-actions-luarocks@v4

      - name: Install & Run LDoc
        run: |
          luarocks install --local ldoc
          ldoc .

      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: nhartland/love-build@v1-beta3
        with:
          app_name: 'love-bed'
          love_version: '11.3'
          source_dir: '.'
      - uses: actions/upload-artifact@v1
        with:
          name: built-application
          path: 'release'
